name: QA Pipeline
on:
  push:
    branches: 
      - qa
    paths:
      - client/**
      - server/**
      - .github/workflows/qa.yml
      
jobs:
  gitleaks-scan:
    name: Gitleaks scan
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v7
      - name: Gitleaks scanner and generate artifacts
        uses: gitleaks/gitleaks-action@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  checkov-scan:
    name: Checkov-scan
    runs-on: ubuntu-latest
    needs: gitleaks-scan
    strategy:
      matrix:
        framework: [terraform, kubernetes, dockerfile]
    steps:
      - name: Git checkout
        uses: actions/checkout@v7
      - name: Checkov ${{ matrix.framework }} scan
        uses: bridgecrewio/checkov-action@v12
        with:
          # This will add both a CLI output to the console and create a results.sarif file
          framework: ${{ matrix.framework }}
          output_format: cli,sarif
          output_file_path: console,checkov-${{ matrix.framework }}-result.sarif
        continue-on-error: true
        
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v2
        if: success() || failure()
        with:
          sarif_file: checkov-${{ matrix.framework }}-result.sarif
          category: checkov-${{ matrix.framework }}   # separates results per framework
      
  trivy-client-fs:
    name: Trivy client fs
    runs-on: ubuntu-latest
    needs: gitleaks-scan
    steps:
      - name: Git checkout
        uses: actions/checkout@v7
  
      - name: Run trivy and generate json report
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          scan-type: 'fs'
          scan-ref: './client'
          ignore-unfixed: true
          format: 'json'
          output: 'trivy-client-fs-results.json'
          severity: 'CRITICAL,HIGH'
  
      - name: Run trivy and generate table report
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          scan-type: 'fs'
          scan-ref: './client'
          ignore-unfixed: true
          format: 'table'
          output: 'trivy-client-fs-results.txt'
          severity: 'CRITICAL,HIGH'
  
      - name: Upload trivy fs reports
        uses: actions/upload-artifact@v7
        with:
          name: trivy-client-fs-reports
          path: |
            trivy-client-fs-results.json
            trivy-client-fs-results.txt
          if-no-files-found: warn

  trivy-server-fs:
    name: Trivy server fs
    runs-on: ubuntu-latest
    needs: gitleaks-scan
    steps:
      - name: Git checkout
        uses: actions/checkout@v7
  
      - name: Run trivy and generate json report
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          scan-type: 'fs'
          scan-ref: './server'
          ignore-unfixed: true
          format: 'json'
          output: 'trivy-server-fs-results.json'
          severity: 'CRITICAL,HIGH'
  
      - name: Run trivy and generate table report
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          scan-type: 'fs'
          scan-ref: './server'
          ignore-unfixed: true
          format: 'table'
          output: 'trivy-server-fs-results.txt'
          severity: 'CRITICAL,HIGH'
  
      - name: Upload trivy fs reports
        uses: actions/upload-artifact@v7
        with:
          name: trivy-server-fs-reports
          path: |
            trivy-server-fs-results.json
            trivy-server-fs-results.txt
          if-no-files-found: warn
        
  client-lint:
    name: Client lint
    runs-on: ubuntu-latest
    needs:
      - checkov-scan
      - trivy-client-fs
    defaults:
      run:
        working-directory: client
    steps:
      - name: Git checkout
        uses: actions/checkout@v7
      - name: Setup nodejs
        uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: 'npm'
          cache-dependency-path: client/package-lock.json
      - name: Install client dependancy
        run: npm ci
      - name: Run client lint
        run: npm run lint --if-present
        continue-on-error: true
        
  server-lint:
    name: Server lint
    runs-on: ubuntu-latest
    needs:
      - checkov-scan
      - trivy-server-fs
    defaults:
      run:
        working-directory: server
    steps:
      - name: Git checkout
        uses: actions/checkout@v7
      - name: Setup nodejs
        uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: 'npm'
          cache-dependency-path: client/package-lock.json
      - name: Install server dependancy
        run: npm ci
      - name: Run server lint
        run: npm run lint --if-present
        continue-on-error: true
  client-test:
    name: Client test
    runs-on: ubuntu-latest
    needs:
      - client-lint
    defaults:
      run:
        working-directory: client
    steps:
      - name: Git checkout
        uses: actions/checkout@v7
      - name: Setup nodejs
        uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: 'npm'
          cache-dependency-path: client/package-lock.json
      - name: Install client dependancy
        run: npm ci
      - name: Run client test
        run: npm run test --if-present
        continue-on-error: true
        
  server-test:
    name: Server test
    runs-on: ubuntu-latest
    needs:
      - server-lint
    defaults:
      run:
        working-directory: server
    steps:
      - name: Git checkout
        uses: actions/checkout@v7
      - name: Setup nodejs
        uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: 'npm'
          cache-dependency-path: client/package-lock.json
      - name: Install server dependancy
        run: npm ci
      - name: Run server test
        run: npm run test --if-present
        continue-on-error: true

  sonarqube:
    name: Sonarqube analysis and quality gate
    runs-on: ubuntu-latest
    needs: 
      - server-test
      - client-test
    steps:
      - uses: actions/checkout@v4
        with:
          # Disabling shallow clone is recommended for improving relevancy of reporting.
          fetch-depth: 0

      # Triggering SonarQube analysis as results of it are required by Quality Gate check.
      - name: SonarQube scan
        uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

      # Check the Quality Gate status.
      - name: SonarQube quality gate check
        id: sonarqube-quality-gate-check
        continue-on-error: true
        uses: sonarsource/sonarqube-quality-gate-action@master
        with:
          pollingTimeoutSec: 600
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

      # Optionally you can use the output from the Quality Gate in another step.
      # The possible outputs of the `quality-gate-status` variable are `PASSED`, `WARN` or `FAILED`.
      - name: "Example show SonarQube Quality Gate Status value"
        run: echo "The Quality Gate status is ${{ steps.sonarqube-quality-gate-check.outputs.quality-gate-status }}"

  # Might have the question after that we will build the image. Then why do we need to build here. Ans: Just make sure
  # that no security and vulnerability left for docker build. (shift left security)
  client-build:
    name: Client webpack build
    runs-on: ubuntu-latest
    needs: client-test
    defaults:
        run:
          working-directory: client
    steps:
      - name: Git checkout
        uses: actions/checkout@v7
      - name: Setup nodejs
        uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: 'npm'
          cache-dependency-path: client/package-lock.json
      - name: Install client dependency
        run: npm ci
      - name: Build client
        run: npm run build --if-present
        continue-on-error: true

  docker:
    name: Docker build and push with trivy scan
    runs-on: ubuntu-latest
    needs: 
      - client-build
      - sonarqube
    steps:
      - name: Git checkout
        uses: actions/checkout@v7
    
      - name: Login to Docker Hub
        uses: docker/login-action@v4
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v4
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4
        
      - name: Build images
        uses: docker/build-push-action@v7
        with:
          context: .
          push: false
          load: true
          tags: |
            iamridoydey/3-tier-app:${{ github.sha }}
            iamridoydey/3-tier-app:latest
      
        
      - name: Run trivy and generate json report
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          scan-type: 'image'
          image-ref: iamridoydey/3-tier-app:${{ github.sha }}
          ignore-unfixed: true
          format: 'json'
          output: 'trivy-docker-image-results.json'
          severity: 'CRITICAL,HIGH'
  
      - name: Run trivy and generate table report
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          scan-type: 'image'
          image-ref: iamridoydey/3-tier-app:${{ github.sha }}
          ignore-unfixed: true
          format: 'table'
          output: 'trivy-docker-image-results.txt'
          severity: 'CRITICAL,HIGH'
  
      - name: Upload trivy docker image reports
        uses: actions/upload-artifact@v7
        with:
          name: trivy-docker-image-reports
          path: |
            trivy-docker-image-results.json
            trivy-docker-image-results.txt
          if-no-files-found: warn
          
      - name: SBOM for docker image
        uses: anchore/sbom-action@v0
        with:
          image: iamridoydey/3-tier-app:${{ github.sha }}
          format: spdx-json
          output-file: image-sbom.spdx.json
          upload-artifact: true
          artifact-name: image-sbom  
        
      - name: Push images
        uses: docker/build-push-action@v7
        with:
          context: .
          push: true
          tags: |
            iamridoydey/3-tier-app:${{ github.sha }}
            iamridoydey/3-tier-app:latest
