apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-ingress
  namespace: prod
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80},{"HTTPS":443}]'
    alb.ingress.kubernetes.io/ssl-redirect: '443'
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:us-east-1:402938031713:certificate/32473cc0-2bb7-4af5-b9f1-5f230ed66384
spec:
  ingressClassName: alb
  rules:
    - host: visitcounter.foo
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: tier-app-svc
                port:
                  number: 5000
