apiVersion: apps/v1
kind: Deployment
metadata:
  name: tier-app
  namespace: prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tier-app
  template:
    metadata:
      labels:
        app: tier-app
    spec:
      imagePullSecrets:
      - name: tier-app-reg-secret-prod
      containers:
      - name: tier-app
        image: iamridoydey/3-tier-app:xyz
        ports:
        - containerPort: 5000
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "250m"
            memory: "256Mi"
        env:
        - name: DB_HOST
          value: mysql
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: MYSQL_DATABASE
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: MYSQL_USER
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: MYSQL_PASSWORD
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: DATABASE_URL
